// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBiP7yGv1lgJC7PxxR71Dupd3HPT0cKtKc',
    appId: '1:283982159648:web:59f20676af5ef050e5c145',
    messagingSenderId: '283982159648',
    projectId: 'crudoperation-fef36',
    authDomain: 'crudoperation-fef36.firebaseapp.com',
    databaseURL: 'https://crudoperation-fef36-default-rtdb.firebaseio.com',
    storageBucket: 'crudoperation-fef36.firebasestorage.app',
    measurementId: 'G-0GHC9Y6LM6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAdyuFEK_PQFEkPW951highAjyfoCXTHCE',
    appId: '1:283982159648:android:e5c460a43d2b5c40e5c145',
    messagingSenderId: '283982159648',
    projectId: 'crudoperation-fef36',
    databaseURL: 'https://crudoperation-fef36-default-rtdb.firebaseio.com',
    storageBucket: 'crudoperation-fef36.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDE8kyJ8ORN5YCc-atIbwvZF8uCN-YsUFI',
    appId: '1:283982159648:ios:4b9e3c6bce9c5d21e5c145',
    messagingSenderId: '283982159648',
    projectId: 'crudoperation-fef36',
    databaseURL: 'https://crudoperation-fef36-default-rtdb.firebaseio.com',
    storageBucket: 'crudoperation-fef36.firebasestorage.app',
    iosBundleId: 'com.example.carmodAr',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDE8kyJ8ORN5YCc-atIbwvZF8uCN-YsUFI',
    appId: '1:283982159648:ios:4b9e3c6bce9c5d21e5c145',
    messagingSenderId: '283982159648',
    projectId: 'crudoperation-fef36',
    databaseURL: 'https://crudoperation-fef36-default-rtdb.firebaseio.com',
    storageBucket: 'crudoperation-fef36.firebasestorage.app',
    iosBundleId: 'com.example.carmodAr',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBiP7yGv1lgJC7PxxR71Dupd3HPT0cKtKc',
    appId: '1:283982159648:web:5975c5855e4c0cfde5c145',
    messagingSenderId: '283982159648',
    projectId: 'crudoperation-fef36',
    authDomain: 'crudoperation-fef36.firebaseapp.com',
    databaseURL: 'https://crudoperation-fef36-default-rtdb.firebaseio.com',
    storageBucket: 'crudoperation-fef36.firebasestorage.app',
    measurementId: 'G-CD9EEE3P15',
  );
}
